### ISSUE TITLE
Refactor OnePortAC and OnePortACBus

### ISSUE THREAD

**Issue by casella** [PowerGrids/PowerGrids#109]
Putting the common parts in OnePortACBase

**Comment by casella** [comment]
We eventually decided to get rid of OnePortACBus

**Comment by AndreaBartolini** [comment]
the solution based on the class refactoring (second in the previous comment) needs to duplicate the 99% of the code of the class `OnePortAC` into the new class `OnePortACbus`. This is not accettable because the `OnePortAC` class contains a lot of code and its duplication may generates issues in the code maintenance activities.

A third solution is to left unchanged the electrical `BaseClasses` structure and to work at Icons level. The dynamic behaviour of the icon text can be implemented directly in the icons, that receive the dynamic values to be shown as inputs.

**Comment by AndreaBartolini** [comment]
Implemented in PR #115

**Comment by AndreaBartolini** [comment]
Regression test successfully done.
