### ISSUE TITLE
Translation errors with examples

### ISSUE THREAD

**Issue by dgusain1** [PowerGrids/PowerGrids#26]
Hi, I am getting the following translation errors on running any example

 Variable S.re not found in scope PowerGrids.Electrical.BaseClasses.PortAC$GEN$port.

I am testing it on OpenModelica 1.16.0

**Comment by casella** [comment]
In order to run the PowerGrids library you need to enable the new frontend in OMEdit. This is the default, but you may have changed that. 

Go to Tools | Options | Simulation and make sure "Enable old front end for code generation" is unchecked. If it is checked, uncheck it, close OMEdit and restart it.

Feel free to reopen the ticket if this doesn't help
